### ISSUE TITLE
Use NER toolkits to replace place and orginaztion to special tokens '<place>','<org>'

### ISSUE THREAD

**Issue by DSXiangLi** [xueyouluo/fsauor2018#11]
想请教下，这种数据预处理的原因是降低无关信息的干扰么？以及大概这一步预处理对最终结果的影响有多大呢？

**Comment by xueyouluo** [comment]
一个是避免OOV问题，另外就是引入额外信息，让模型直接知道这是地址等信息。应该差别不大，替换的话可能的问题是一些地址信息量会比较大，比如是在热门商圈，但是替换后就丢掉了







  	
 罗学优 
杭州艾耕科技有限公司  
 ***@***.*** 
 地址：B2 副楼 1楼 
	     
	   		 杭州艾耕科技有限公司  	 企业主页  		      
 信息安全声明：本邮件包含信息归发件人所在组织所有，发件人所在组织对该邮件拥有所有权利。
请接收者注意保密，未经发件人书面许可，不得向任何第三方组织和个人透露本邮件所含信息的全部或部分。以上声明仅适用于工作邮件。
Information Security Notice: The information contained in this mail is solely property of the sender's organization. 
This mail communication is confidential. Recipients named above are obligated to maintain secrecy and are not permitted to disclose the contents of this communication to others.  ------------------------------------------------------------------
***@***.***>
日　期：2021年09月26日 19:27:17
***@***.***>
***@***.***>
主　题：[xueyouluo/fsauor2018] Use NER toolkits to replace place and orginaztion to special tokens '<place>','<org>' (#11)

想请教下，这种数据预处理的原因是降低无关信息的干扰么？以及大概这一步预处理对最终结果的影响有多大呢？
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DSXiangLi** [comment]
@xueyouluo 明白啦感谢～
